[general]
import = [
    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[window]
dynamic_padding = false

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium" }
size = 13

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]

[debug]
renderer = "glsl3"
